// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDklj2QIBO21nnl-bLaoR8hUD3BjOlWq24',
    appId: '1:202149297195:web:3235385530515d13177e6e',
    messagingSenderId: '202149297195',
    projectId: 'test-app-dd439',
    authDomain: 'test-app-dd439.firebaseapp.com',
    storageBucket: 'test-app-dd439.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Dj6AJCen6TNS72MtAiK1aaeDciK3-aM',
    appId: '1:202149297195:android:594d254db51d7dd5177e6e',
    messagingSenderId: '202149297195',
    projectId: 'test-app-dd439',
    storageBucket: 'test-app-dd439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKnqjhdLhkGFjplNBF2ceRQvlp1zeV0l0',
    appId: '1:202149297195:ios:b4429241519ae5be177e6e',
    messagingSenderId: '202149297195',
    projectId: 'test-app-dd439',
    storageBucket: 'test-app-dd439.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKnqjhdLhkGFjplNBF2ceRQvlp1zeV0l0',
    appId: '1:202149297195:ios:b4429241519ae5be177e6e',
    messagingSenderId: '202149297195',
    projectId: 'test-app-dd439',
    storageBucket: 'test-app-dd439.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDklj2QIBO21nnl-bLaoR8hUD3BjOlWq24',
    appId: '1:202149297195:web:df50e69df6dcb771177e6e',
    messagingSenderId: '202149297195',
    projectId: 'test-app-dd439',
    authDomain: 'test-app-dd439.firebaseapp.com',
    storageBucket: 'test-app-dd439.appspot.com',
  );
}
